version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into AWS ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 676206934360.dkr.ecr.us-east-1.amazonaws.com
      - echo "Logging into Docker Hub"
      - docker login --username AnjalyVincent --password Anjaly@1992

  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t network .
      - docker tag network:latest 676206934360.dkr.ecr.us-east-1.amazonaws.com/anjaly:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push 676206934360.dkr.ecr.us-east-1.amazonaws.com/anjaly:latest
      - echo "Saving build artifacts"
      - mkdir -p mypipeline/BuildArtif
      - echo "Build successful" > mypipeline/BuildArtif/build_info.txt

artifacts:
  files:
    - "mypipeline/BuildArtif/*"
  discard-paths: no
A
