version: 0.2
environment_variables:
  REPOSITORY_URI: "https://github.com/Anjaly-Vincent1992/terraform.git"
  IMAGE_TAG: "v1.0"

phases:
  build:
    commands:
      # Build Docker image
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f Dockerfile .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      # Push Docker image to Amazon ECR
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - '/*'                        # Include all files in the repository
    - 'install_dependencies.sh'    # Include install_dependencies.sh script
    - 'start_docker_container.sh'  # Include start_docker_container.sh script
    - 'stop_docker_container.sh'   # Include stop_docker_container.sh script
  discard-paths: yes  # This removes folder structure in the final artifact (scripts will be at the root level)

cache:
  paths:
    - '/root/.cache/pip//*'   # Cache pip packages to speed up subsequent builds
